import type { Metadata } from 'next'
import { Geist, Geist_Mono, Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/components/navbar/Navbar'
import { Toaster } from '@/components/ui/sonner'
import { CartStoreProvider } from '@/providers/cart-store-provider'
import { syncUser } from '@/db/utils/sync-user'
import { StoreCurrencyProvider } from '@/providers/store-currency-provider'
import { getExchangeRates } from '@/lib/currency'
import { getStoreCurrency } from '@/lib/currency.server'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  await syncUser()
  const exchangeRates = await getExchangeRates()
  const { currency: initialCurrency } = await getStoreCurrency()
  return (
    <ClerkProvider>
      <html
        lang='en'
        className={cn(
          'h-full',
          'antialiased',
          geistSans.variable,
          geistMono.variable,
          'font-sans',
          inter.variable
        )}
      >
        <body className='min-h-screen flex flex-col'>
          <StoreCurrencyProvider exchangeRates={exchangeRates} initialCurrency={initialCurrency}>
            <CartStoreProvider>
              <Navbar />
              {children}
              <Toaster richColors />
            </CartStoreProvider>
          </StoreCurrencyProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
